# Generated by Django 5.2.1 on 2025-05-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nombre_empresa',
            field=models.CharField(default='Empresa Temporal', max_length=255, verbose_name='Nombre de la Empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, null=True, verbose_name='Género'),
        ),
    ]
