# Generated by Django 5.2.1 on 2025-07-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_dialaborable_remove_cliente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
