# Generated by Django 5.2.1 on 2025-07-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Usado'),
        ),
    ]
