# Generated by Django 5.2.1 on 2025-07-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_passwordresetcode_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email_empresa',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico de la Empresa'),
        ),
    ]
