# Generated by Django 5.2.1 on 2025-08-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_servicio_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
