# Generated by Django 5.2.1 on 2025-08-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_empresa_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_empresa',
            field=models.CharField(choices=[('Peluquería', 'Peluquería'), ('Hotel', 'Hotel'), ('Salón', 'Salón de Belleza'), ('Spa', 'Spa'), ('Barbería', 'Barbería'), ('Veterinaria', 'Veterinaria'), ('Clínica', 'Clínica'), ('Tienda', 'Tienda'), ('Centro', 'Centro'), ('Otros', 'Otros')], max_length=50, verbose_name='Tipo de Empresa'),
        ),
    ]
